name: Toggle GitHub Pages

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Enter "live" or "dead"'
        required: true

jobs:
  toggle-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Toggle GitHub Pages State
        env:
          GH_TOKEN: ${{ secrets.PAGES_TOGGLE_PAT }}
          REPO: ${{ github.repository }}
          MODE: ${{ github.event.inputs.mode }}
        run: |
          echo "Requested mode: $MODE"

          if [ "$MODE" = "dead" ]; then
            echo "Disabling Pages..."
            curl -i -X DELETE \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/$REPO/pages
            echo "✔️ Pages disabled (should go 404)."

          elif [ "$MODE" = "live" ]; then
            echo "Enabling Pages..."
            curl -i -X POST \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/$REPO/pages \
              -d '{"source":{"branch":"main","path":"/"}}'
            echo "✔️ Pages re-enabled (should go LIVE)."

          else
            echo "❌ Invalid mode. Use live or dead."
            exit 1
          fi
