name: Toggle GitHub Pages

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Mode (live or dead)'
        required: true

jobs:
  toggle:
    runs-on: ubuntu-latest
    steps:
      - name: Toggle GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.PAGES_TOGGLE_PAT }}
          REPO: ${{ github.repository }}
          MODE: ${{ github.event.inputs.mode }}
        run: |
          echo "Mode: $MODE"

          if [ "$MODE" = "dead" ]; then
            curl -X DELETE \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/$REPO/pages
            echo "❌ GitHub Pages disabled"
          elif [ "$MODE" = "live" ]; then
            curl -X POST \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/$REPO/pages \
              -d '{"source":{"branch":"main","path":"/"}}'
            echo "✅ GitHub Pages re-enabled"
          else
            echo "Invalid mode"
            exit 1
          fi
