name: 🔁 Toggle Repo Visibility

on:
  push:
    branches:
      - toggle-visibility  # 👈 When you push to this branch, it toggles visibility

jobs:
  toggle-visibility:
    runs-on: ubuntu-latest

    steps:
      - name: 🧠 Toggle public/private repo
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}  # 👈 Add your PAT in repo secrets as GH_PAT
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          echo "🔍 Checking current visibility..."

          current_visibility=$(curl -s -H "Authorization: token $GH_TOKEN" https://api.github.com/repos/$OWNER/$REPO | jq '.private')

          if [ "$current_visibility" = "true" ]; then
            new_visibility="false"
            echo "📤 Repo is currently PRIVATE. Making it PUBLIC..."
          else
            new_visibility="true"
            echo "📥 Repo is currently PUBLIC. Making it PRIVATE..."
          fi

          curl -X PATCH \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$OWNER/$REPO \
            -d "{\"private\": $new_visibility}"
